from typing import Final

EMAIL_CONFLICT_SYSTEM_CODE: Final[str] = "EMAIL_ALREADY_EXISTS"
EMAIL_VERIFY_CODE_EXPIRED_SYSTEM_CODE: Final[str] = "VERIFY_CODE_EXPIRED"
EMAIL_AUTH_NUMBER_INVALID_SYSTEM_CODE: Final[str] = "AUTH_NUMBER_INVALID"
PASSWORD_INVALID_SYSTEM_CODE: Final[str] = "PASSWORD_INVALID"
