from typing import Final

EMAIL_CONFLICT_SYSTEM_CODE: Final[str] = "EMAIL_ALREADY_EXISTS"
EMAIL_VERIFY_CODE_EXPIRED_SYSTEM_CODE: Final[str] = "VERIFY_CODE_EXPIRED"
EMAIL_AUTH_NUMBER_INVALID_SYSTEM_CODE: Final[str] = "AUTH_NUMBER_INVALID"
PASSWORD_INVALID_SYSTEM_CODE: Final[str] = "PASSWORD_INVALID"

USER_PROFILE_REQUIRED_SYSTEM_CODE: Final[str] = "USER_PROFILE_DATA_REQUIRED"
USER_NOT_FOUND_SYSTEM_CODE: Final[str] = "USER_NOT_FOUND"

BANNER_NOT_FOUND_SYSTEM_CODE: Final[str] = "BANNER_NOT_FOUND"

FAQ_NOT_FOUND_SYSTEM_CODE: Final[str] = "FAQ_NOT_FOUND"

MATCH_NOT_FOUND_SYSTEM_CODE: Final[str] = "MATCH_NOT_FOUND"

GUEST_NOT_FOUND_SYSTEM_CODE: Final[str] = "GUEST_NOT_FOUND"
